package dev.fincke.hopper.order.buyer;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import org.hibernate.annotations.UuidGenerator;

import java.util.Objects;
import java.util.UUID;

// Entity mapped to "buyers" table with email index for fast lookups
@Entity
@Table(
    name = "buyers",
    indexes = {
        @Index(name = "idx_buyers_email", columnList = "email")
    }
)
public class Buyer
{
    // * Attributes

    // UUID primary key (auto-generated by Hibernate)
    @Id
    @GeneratedValue
    @UuidGenerator
    private UUID id;

    // Email address of buyer (nullable, validated with @Email)
    @Email
    @Column(name = "email", nullable = true)
    private String email;

    // Display name of buyer (required, stored trimmed)
    @NotBlank
    @Column(name = "name", nullable = false)
    private String name = "";

    // * Constructors
    
    // Default constructor required by JPA
    protected Buyer() {}

    // Main constructor for creating new buyers
    public Buyer(String email, String name)
    {
        // Normalize email to lowercase for consistency
        this.email = email == null ? null : email.trim().toLowerCase();
        // Require non-null name and trim whitespace
        this.name = Objects.requireNonNull(name, "name").trim();
    }

    // * Getters and Setters
    
    // buyer ID
    public UUID getId()
    {
        return id;
    }

    // buyer ID (primarily used by JPA)
    public void setId(UUID id)
    {
        this.id = id;
    }

    // email
    public String getEmail()
    {
        return email;
    }

    // email (normalized to lowercase on set)
    public void setEmail(String email)
    {
        this.email = email == null ? null : email.trim().toLowerCase();
    }

    // name
    public String getName()
    {
        return name;
    }

    // name (trims whitespace on set)
    public void setName(String name)
    {
        this.name = name == null ? null : name.trim();
    }

    // * Overrides
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof Buyer other)) return false;
        // Two buyers are equal if they have the same ID (ID-based equality for JPA entities)
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode()
    {
        // Use ID for hash code, or 0 if not persisted yet
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public String toString()
    {
        return "Buyer{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", name='" + name + '\'' +
                '}';
    }
}