package dev.fincke.hopper.order.address;

import dev.fincke.hopper.order.order.Order;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import org.hibernate.annotations.UuidGenerator;

import java.util.Objects;
import java.util.UUID;

// Entity mapped to "order_addresses" table with order constraint and geographic indexes
@Entity
@Table(
    name = "order_addresses",
    uniqueConstraints = {@UniqueConstraint(name = "uq_order_addresses_order", columnNames = {"order_id"})},
    indexes = {
        @Index(name = "idx_order_addresses_city", columnList = "city")
    }
)
public class OrderAddress
{
    // * Attributes

    // UUID primary key (auto-generated by Hibernate)
    @Id
    @GeneratedValue
    @UuidGenerator
    private UUID id;

    // each address belongs to exactly one order (one-to-one relationship)
    @OneToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    // street address (required, stored trimmed)
    @NotBlank
    @Column(name = "street", nullable = false)
    private String street = "";

    // city name (required, indexed for geographic queries)
    @NotBlank
    @Column(name = "city", nullable = false)
    private String city = "";

    // state/region/province (required, varies by country)
    @NotBlank
    @Column(name = "state", nullable = false)
    private String state = "";

    // postal/zip code (required, US format validation)
    @NotBlank
    @Column(name = "postal_code", nullable = false)
    private String postalCode = "";

    // country associated with the address (ISO code preferred)
    @NotBlank
    @Column(name = "country", nullable = false)
    private String country = "";

    // * Constructors
    
    // Default constructor required by JPA
    protected OrderAddress()
    {}

    // Main constructor for creating new addresses with validation
    public OrderAddress(Order order,
                       String street,
                       String city,
                       String state,
                       String postalCode,
                       String country)
    {
        // Validate required order relationship
        this.order = Objects.requireNonNull(order, "order");
        // Trim all address fields for consistency
        this.street = Objects.requireNonNull(street, "street").trim();
        this.city = Objects.requireNonNull(city, "city").trim();
        this.state = Objects.requireNonNull(state, "state").trim();
        this.postalCode = Objects.requireNonNull(postalCode, "postalCode").trim();
        this.country = Objects.requireNonNull(country, "country").trim();
    }

    // * Getters and Setters
    
    // address ID
    public UUID getId()
    {
        return id;
    }

    // address ID (primarily used by JPA)
    public void setId(UUID id)
    {
        this.id = id;
    }

    // order
    public Order getOrder()
    {
        return order;
    }

    // order (updates relationship)
    public void setOrder(Order order)
    {
        this.order = order;
    }

    // street
    public String getStreet()
    {
        return street;
    }

    // street (trims whitespace on set)
    public void setStreet(String street)
    {
        this.street = street == null ? null : street.trim();
    }

    // city
    public String getCity()
    {
        return city;
    }

    // city (trims whitespace on set)
    public void setCity(String city)
    {
        this.city = city == null ? null : city.trim();
    }

    // state
    public String getState()
    {
        return state;
    }

    // state (trims whitespace on set)
    public void setState(String state)
    {
        this.state = state == null ? null : state.trim();
    }

    // postal code
    public String getPostalCode()
    {
        return postalCode;
    }

    // postal code (trims whitespace on set)
    public void setPostalCode(String postalCode)
    {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    // country
    public String getCountry()
    {
        return country;
    }

    // country (trims whitespace on set)
    public void setCountry(String country)
    {
        this.country = country == null ? null : country.trim();
    }

    // * Overrides
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof OrderAddress other)) return false;
        // Two addresses are equal if they have the same ID (ID-based equality for JPA entities)
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode()
    {
        // Use ID for hash code, or 0 if not persisted yet
        return id != null ? id.hashCode() : 0;
    }

    @Override
    public String toString()
    {
        return "OrderAddress{" +
                "id=" + id +
                ", street='" + street + '\'' +
                ", city='" + city + '\'' +
                ", state='" + state + '\'' +
                ", postalCode='" + postalCode + '\'' +
                ", country='" + country + '\'' +
                '}';
    }
}
